### ISSUE TITLE
Example labelled data

### ISSUE THREAD

**Issue by vigji** [DownesLab/Marigold#2]
Hi! It is me again!

I think that having the example data was very useful in figuring out the video format. However, to try out the whole pipeline it would be great if you could share also an example of annotated data over which an example network of defined parameters could be trained - I guess in the form of a `.marigold` file. do you think that would be possible?

**Comment by downeslab** [comment]
Thanks for your feedback. I've added some example datasets.

**Comment by vigji** [comment]
Great, thank you very much!
