### ISSUE TITLE
Unable to overwrite existing dataset

### ISSUE THREAD

**Issue by vigji** [DownesLab/Marigold#3]
If I load a dataset and I annotate some new frames, I am then unable to overwrite the existing dataset, getting this message:

<img width="384" alt="Screenshot 2024-06-25 at 06 06 50" src="https://github.com/downeslab/marigold/assets/10400212/cfc4d093-b125-4570-aa3f-dafb425c5c58">

Not sure how I can grant such permissions though.

Also, there is no option to save under a different filename after having started an annotation, as far as I can see. This is problematic as the error above makes you trash an entire labelling session

**Comment by downeslab** [comment]
Thanks for pointing out this problem. It should now be resolved.
