### ISSUE TITLE
Empty or corrupt results file?

### ISSUE THREAD

**Issue by vigji** [DownesLab/Marigold#5]
I tried to run training using the labels available in the examples. After training (a short version of it) I go to `Analysis`, and process the example video using the trained network. Things looks reasonable. 

Then I go to `Export data and visualizations`: I get a reasonable plot on the right (see below, was playing with a square arena instead of circular):
<img width="1495" alt="Screenshot 2024-06-25 at 07 07 14" src="https://github.com/downeslab/marigold/assets/10400212/327291cd-1ebd-46c9-9b84-33901290ae8e">

However, when I press "Export results" I get what seems to be an empty or problematic `results.zip` file that I enclose here:
[results.zip](https://github.com/user-attachments/files/15964969/results.zip). 

I tried to unzip it with macOS utility, python and online tools and everything tells me there is something wrong with it. What did I do wrong?

Thanks in advance for the help!

**Comment by downeslab** [comment]
Thanks for bringing this to my attention. It seems that the exported results files were working with some unzipping methods but not others. After making some updates the files should be more broadly compatible now.

**Comment by downeslab** [comment]
Thanks for bringing this to my attention. It seems that the exported results files were working with some unzipping methods but not others. The files should be more broadly compatible now.
